name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "💥 重大变更"
    labels:
      - "major"
  - title: "🚀 新功能"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 杂项维护"
    labels:
      - "chore"
      - "dependencies"
autolabeler:
  - label: "chore"
    branch:
      - "/maint\/.+/"
      - "/chore\/.+/"
  - label: "bug"
    branch:
      - "/fix\/.+/"
  - label: "enhancement"
    branch:
      - "/feature\/.+/"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: "\\<*_&" # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |

  $CHANGES
